gnet/urls.py
from django.urls import include, path
from . import views, api_views

app_name = 'gnet'

urlpatterns = [
    path('token/', views.TokenQuery.as_view(), name='token'),
    path('textparser/', views.TextParser.as_view(), name='textparser'),
    path('lemmatize/', views.Lemmatize.as_view(), name='lemmatize'),
    path('lemma/', api_views.lemma, name='lemma'),
    path('synset/', api_views.synset, name='synset'),
    path('textparser-api/', api_views.textparser, name='textparser-api'),

]

places/models.py
import re
from django.db import models
from django.core.urlresolvers import reverse
from idprovider.models import IdProvider


class AlternativeName(IdProvider):
    name = models.CharField(max_length=250, blank=True, help_text="Alternative Name")

    def get_absolute_url(self):
        return reverse('places:alternativename_detail', kwargs={'pk': self.id})

    @classmethod
    def get_listview_url(self):
        return reverse('browsing:browse_altnames')

    @classmethod
    def get_createview_url(self):
        return reverse('places:alternativename_create')

    def get_next(self):
        next = AlternativeName.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = AlternativeName.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return prev.first().id
        return False

    def get_absolute_url(self):
        return reverse('places:alternativename_detail', kwargs={'pk': self.id})

    def __str__(self):
        return "{}".format(self.name)


class Place(IdProvider):
    PLACE_TYPES = (
        ("city", "city"),
        ("country", "country")
    )

    """Holds information about places."""
    name = models.CharField(
        max_length=250, blank=True, help_text="Normalized name"
    )
    alternative_name = models.ManyToManyField(
        AlternativeName,
        max_length=250, blank=True,
        help_text="Alternative names"
    )
    geonames_id = models.CharField(
        max_length=50, blank=True,
        help_text="GND-ID"
    )
    lat = models.DecimalField(
        max_digits=20, decimal_places=12,
        blank=True, null=True
    )
    lng = models.DecimalField(
        max_digits=20, decimal_places=12, blank=True, null=True
    )
    part_of = models.ForeignKey(
        "Place", null=True, blank=True,
        help_text="A place (country) this place is part of.",
        related_name="has_child"
    )
    place_type = models.CharField(choices=PLACE_TYPES, null=True, blank=True, max_length=50)

    def get_geonames_url(self):
        if self.geonames_id.startswith('ht') and self.geonames_id.endswith('.html'):
            return self.geonames_id
        else:
            return "http://www.geonames.org/{}".format(self.geonames_id)

    def get_geonames_rdf(self):
        try:
            number = re.findall(r'\d+', str(self.geonames_id))[0]
            return None
        except:
            return None

    @classmethod
    def get_listview_url(self):
        return reverse('browsing:browse_places')

    @classmethod
    def get_createview_url(self):
        return reverse('places:place_create')

    @classmethod
    def get_arche_dump(self):
        return reverse('browsing:rdf_places')

    def get_next(self):
        next = Place.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = Place.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return prev.first().id
        return False

    def get_absolute_url(self):
        return reverse('places:place_detail', kwargs={'pk': self.id})

    def __str__(self):
        return "{}".format(self.name)


class Institution(IdProvider):
    legacy_id = models.CharField(max_length=300, blank=True)
    written_name = models.CharField(max_length=300, blank=True)
    authority_url = models.CharField(max_length=300, blank=True)
    alt_names = models.CharField(max_length=300, blank=True)
    abbreviation = models.CharField(max_length=300, blank=True)
    location = models.ForeignKey(Place, blank=True, null=True)
    parent_institution = models.ForeignKey(
        'Institution', blank=True, null=True, related_name='children_institutions')
    comment = models.TextField(blank=True)

    @classmethod
    def get_arche_dump(self):
        return reverse('browsing:rdf_institutions')

    @classmethod
    def get_listview_url(self):
        return reverse('browsing:browse_institutions')

    @classmethod
    def get_createview_url(self):
        return reverse('places:institution_create')

    def get_absolute_url(self):
        return reverse('places:institution_detail', kwargs={'pk': self.id})

    def get_next(self):
        next = Institution.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = Institution.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return prev.first().id
        return False

    def __str__(self):
        return "{}".format(self.written_name)


class Person(IdProvider):
    legacy_id = models.CharField(max_length=300, blank=True)
    written_name = models.CharField(max_length=300, blank=True)
    forename = models.CharField(max_length=300, blank=True)
    name = models.CharField(max_length=300, blank=True)
    acad_title = models.CharField(max_length=300, blank=True)
    alt_names = models.CharField(max_length=300, blank=True)
    belongs_to_institution = models.ForeignKey(
        Institution, blank=True, null=True, related_name="has_member"
    )
    authority_url = models.CharField(max_length=300, blank=True)
    comment = models.TextField(blank=True)

    @classmethod
    def get_createview_url(self):
        return reverse('places:person_create')

    @classmethod
    def get_listview_url(self):
        return reverse('browsing:browse_persons')

    @classmethod
    def get_arche_dump(self):
        return reverse('browsing:rdf_persons')

    def get_absolute_url(self):
        return reverse('places:person_detail', kwargs={'pk': self.id})

    def get_next(self):
        next = Person.objects.filter(id__gt=self.id)
        if next:
            return next.first().id
        return False

    def get_prev(self):
        prev = Person.objects.filter(id__lt=self.id).order_by('-id')
        if prev:
            return prev.first().id
        return False

    def __str__(self):
        return "{}".format(self.written_name)

places/templates/places/alternativenames_create.html
{% extends "webpage/base.html" %}
{% block Title %} Create/Modify Alternative Name {% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<div class="panel panel-default">
    <div class="panel-heading">
        <h1>Create/Edit Alternative Name</h1>
    </div>
    <div class="panel-body">
        <form action="" method="post">
            {% csrf_token %}
            {% crispy form %}
            {% if object %}
            <a class ="btn btn-danger btn-sm" href="{% url 'places:alternativename_delete' pk=object.id %}">delete</a>
            {% endif %}
        </form>
   </div>
</div>
</div>
{% endblock content %}

places/templates/places/alternativenames_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Title %}Edit Places{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to
include 'autocomplete_light/static.html
-->
<!--leafletjs -->
<link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
<script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
<style>
#map { height: 500px; }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <div class="panel panel-default procustom-panel-create">
        <div class="panel-heading procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                    <h2>
                        <a href="{% url 'places:alternativename_detail' pk=object.get_prev %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true" title="previous"></span></a>
                    </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>alternative name:</small> {{ object.name }}
                        {% if user.is_authenticated %}
                        <small><a href="{% url 'places:alternativename_edit' pk=object.id %}">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="edit"></span>
                        </a>
                    </small>
                    {% endif %}
                </h1>
            </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'places:alternativename_detail' pk=object.get_next %}" style="float:right"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true" title="next"></span></a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="panel-body">
                <legend>About</legend>
                <table class="table table-bordered table-hover">
                <tr>
                    <th>related places</th>
                    <td>
                        <ul>
                            {% for x in object.related_places.all %}
                            {% if x.id %}
                            <li><a href="{% url 'places:place_detail' pk=x.id %}">{{ x }}</a></li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</div>
{% endblock %}

places/templates/places/edit_places.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Title %}Edit Places{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to 
    include 'autocomplete_light/static.html
-->
<!--leafletjs -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

{% if object %}
<div class="row">
    <div class="col-md-4">
{% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                  <h3>{%if object %} Edit {% else %} Create {% endif %}</h3>
            </div>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% crispy form %}
                    {% if object %}
                    <a class="btn btn-default btn-block" target="_blank">Check<span id="currentID"></span></a>
                    {% endif %}
                    <input class="btn btn-primary btn-block" type="submit" value="Save" />
                    {% if object %}
                    <a class ="btn btn-danger btn-sm" href="{% url 'places:place_delete' pk=object.id %}">delete</a>
                    {% endif %}
                </form>
           </div>
       </div>
{% if object %}       
   </div>
    <div class ="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <form class="form-group">
                    <select class="form-control" id="geonamesSELECT">
                            {% if object.geonames_id or object.lat %}
                                <option id="geonamesOption" value="{{ object.name }}_{{ object.lat }}_{{ object.lng }}_{{ object.geonames_id }}">DB-Entry | {{ object.name }} | {{ object.lat }} | {{ object.lng }} | {{ object.geonames_id }}</option>
                            {% endif %}
                            {% for dict in responseJSON %}
                            <option id="geonamesOption" value="{{ dict.countryName }}_{{ dict.name }}_{{ dict.lat }}_{{ dict.lng }}_{{ dict.geonameId }}"> {{ dict.countryName }} | {{ dict.name }} | {{ dict.lat }} | {{ dict.lng }} | {{ dict.geonameId }}</option>
                            {% endfor %}
                        </select>
                    </form>
            </div>
            <div class="panel-body">
                <div id="parentMap"></div>
            </div>
        </div>
    </div>
</div>
{% endif %}


<script type="text/javascript">
    $(document).ready(function(){
        $("#id_alias_name-autocomplete").after('<button id="add_aliasName" type="button" class="btn btn-sm btn-success" onclick="popupCreateName()"><span class="glyphicon glyphicon-plus" /></button>');
    });
    $(document).ready(function(){
        $("#id_alternative_name-autocomplete").after('<button id="add_alternativeName" type="button" class="btn btn-sm btn-success" onclick="popupCreateName()"><span class="glyphicon glyphicon-plus"/></button>');
    });
</script>

<script type="text/javascript">
    $( document ).ready(function() {
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 10);

       L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);

        L.marker([gps1, gps2]).addTo(map)
        .bindPopup(placeName)
        .openPopup();
        });
</script>

<script type="text/javascript">
    $( document ).ready(function(){
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
        var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

    });
</script>

<script type="text/javascript">
    $("#geonamesSELECT").change(function(){
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
       var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 15);
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
       var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

       L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);
        
        L.marker([gps1, gps2]).addTo(map)
            .bindPopup(placeName)
            .openPopup();
});
</script>
{% endblock %}

places/templates/places/institution_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Title %}Edit Places{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to
include 'autocomplete_light/static.html
-->
<!--leafletjs -->
<link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
<script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
<style>
#map { height: 500px; }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <div class="panel panel-default procustom-panel-create">
        <div class="panel-heading procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                    <h2>
                        <a href="{% url 'places:institution_detail' pk=object.get_prev %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true" title="previous"></span></a>
                    </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>institution:</small> {{ object }}
                        {% if user.is_authenticated %}
                        <small><a href="{% url 'places:institution_edit' pk=object.id %}">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="edit"></span>
                        </a>
                    </small>
                    {% endif %}
                </h1>
            </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'places:institution_detail' pk=object.get_next %}" style="float:right"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true" title="next"></span></a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <legend>About</legend>
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>
                            Name
                        </th>
                        <td>
                            {{ object.written_name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            authority_url
                        </th>
                        <td>
                            <a href="{{ object.authority_url }}">{{ object.authority_url }}</a>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            alt_names
                        </th>
                        <td>
                            {{ object.alt_names }}
                        </td>
                    </tr>
                    {% if object.parent_institution %}
                        <tr>
                            <th>
                                parent_institution
                            </th>
                            <td>
                                <a href="{{ object.parent_institution.get_absolute_url }}">{{ object.parent_institution }}</a>
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.children_institutions.all %}
                        <tr>
                            <th>
                                children_institutions
                            </th>
                            <td>
                                <ul>
                                    {% for x in object.children_institutions.all %}
                                        <li>
                                            <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>

                            </td>
                        </tr>
                    {% endif %}
                    {% if object.location %}
                        <tr>
                            <th>
                                location
                            </th>
                            <td>
                                <a href="{{ object.location.get_absolute_url }}">{{ object.location }}</a>
                            </td>
                        </tr>
                    {% endif %}
                </table>
                <legend>Related Persons</legend>
                <ul>
                    {% for x in object.has_member.all %}
                    <li>
                        <a href="{{ x.get_absolute_url }}">{{ x }}</a>
                    </li>
                    {% endfor %}
                </ul>

                {% if user.is_authenticated %}
                    <a class="btn btn-danger" href="{% url 'places:institution_delete' pk=object.id %}">delete</a>
                {% endif %}
            </div>
            <div class="col-md-6">
                <div id="map"/>
            </div>
        </div>
    </div>
</div>
</div>

<script type="text/javascript">
$( document ).ready(function() {
    var placeName = "{{ object.location.name }}"
    var lat = "{{ object.location.lat }}"
    var lng = "{{ object.location.lng }}"
    var map = L.map('map').setView([lat, lng], 10);

    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
    }).addTo(map);

    L.marker([lat, lng]).addTo(map)
    .bindPopup(placeName)
    .openPopup();
});
</script>
{% endblock %}

places/templates/places/list_places.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Title %}List of Places{% endblock %}

{% block scriptHeader %}<!--leafletjs -->
    <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
    <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}
{% block content %}
{% if object_list %}
  <div class="row">
    <div class="col-md-4">
        <div class="panel panel-default panel-fixed" >
            <div class="panel-heading" style="text-align:center;">
                <h3>Places</h3>
          {% if user.is_authenticated %}
            <a href="{% url 'places:place_create' %}">(add another Place)</a>
          {% endif %}
            </div>
            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>GeoNames</th>
                        </th>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                        <tr>
                            <td>
                {% if user.is_authenticated %}
                  <a href="{% url 'places:place_edit' pk=object.id %}">{{ object }} (edit)</a>
                  {% else %}
                  {{ object }}
                {% endif %}
              </td>
                            <td>{{ object.geonames_id }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading" style="text-align:center;">
                <h3>Geovisualisation</h3>
            </div>
            <div class="panel-body">
                <div id="parentMap"></div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $( document ).ready(function() {
         $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");

        var map = L.map('map').setView([48.69096, 9.14062], 5);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
        }).addTo(map);

        {% for object in object_list %}
        {% if object.lat %}
        L.marker([{{ object.lat }}, {{ object.lng }}])
        .addTo(map)
        .bindPopup("<h1>{{ object.name }}</h1> <table class='table table-striped'> <tr> <td>Name: </td> <td>{{ object.name }}</td> </tr> </table>");
        {% endif %}
        {% endfor %}
        });
</script>
{% else %}

  {% if user.is_authenticated %}
  <div class="panel panel-default">
        <div class="panel-heading">
            <h1>Places</h1>
            <div>
                <a class="btn btn-primary" href="{% url 'places:place_create' %}" role="button">
                    crate a new location/place
                </a>
            </div>
            <br />
        </div>
        <div class="panel-body">
        </div>
    </div>

  {% endif %}
{% endif %}
{% endblock %}

places/templates/places/person_detail.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block Title %}Person{% endblock %}

{% block scriptHeader %}
<!-- In case you are using any autocomplete-functions, don´t forget to
include 'autocomplete_light/static.html
-->
<!--leafletjs -->
<link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}" />
<script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
<style>
#map { height: 500px; }
</style>
{% endblock %}

{% block content %}

<div class="container">
    <div class="panel panel-default procustom-panel-create">
        <div class="panel-heading procustom-panel-heading">
            <div class="row">
                <div class="col-md-2">
                    {% if object.get_prev %}
                    <h2>
                        <a href="{% url 'places:person_detail' pk=object.get_prev %}"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true" title="previous"></span></a>
                    </h2>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h1 style="text-align: center;">
                        <small>person:</small> {{ object }}
                        {% if user.is_authenticated %}
                        <small><a href="{% url 'places:person_edit' pk=object.id %}">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true" title="edit"></span>
                        </a>
                    </small>
                    {% endif %}
                </h1>
            </div>
            <div class="col-md-2">
                <h2>
                    {% if object.get_next %}
                    <a href="{% url 'places:person_detail' pk=object.get_next %}" style="float:right"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true" title="next"></span></a>
                </h2>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
                <legend>About</legend>
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>
                            written_name
                        </th>
                        <td>
                            {{ object.written_name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            forename
                        </th>
                        <td>
                            {{ object.forename }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            name
                        </th>
                        <td>
                            {{ object.name }}
                        </td>
                    </tr>
                    {% if object.authority_url %}
                        <tr>
                            <th>
                                authority_url
                            </th>
                            <td>
                                <a href="{{ object.authority_url }}">{{ object.authority_url }}</a>
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.belongs_to_institution %}
                        <tr>
                            <th>
                                belongs_to_institution
                            </th>
                            <td>
                                <a href="{{ object.belongs_to_institution.get_absolute_url }}">{{ object.belongs_to_institution }}</a>
                            </td>
                        </tr>
                    {% endif %}
                </table>
                {% if user.is_authenticated %}
                    <a class="btn btn-danger" href="{% url 'places:person_delete' pk=object.id %}">delete</a>
                {% endif %}
            </div>
            <div class="col-md-6">
                <div id="map"/>
            </div>
        </div>
    </div>
</div>
</div>

<script type="text/javascript">
$( document ).ready(function() {
    var placeName = "{{ object.belongs_to_institution.written_name }}"
    var lat = "{{ object.belongs_to_institution.location.lat }}"
    var lng = "{{ object.belongs_to_institution.location.lng }}"
    var map = L.map('map').setView([lat, lng], 10);

    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1Ijoic2VubmllcmVyIiwiYSI6ImNpbHk1YWV0bDAwZnB2dW01d2l1Y3phdmkifQ.OljQLEhqeAygai2y6VoSwQ'
    }).addTo(map);

    L.marker([lat, lng]).addTo(map)
    .bindPopup(placeName)
    .openPopup();
});
</script>
{% endblock %}