gnet/urls.py
from django.urls import include, path
from . import views, api_views

app_name = 'gnet'

urlpatterns = [
    path('token/', views.TokenQuery.as_view(), name='token'),
    path('textparser/', views.TextParser.as_view(), name='textparser'),
    path('lemmatize/', views.Lemmatize.as_view(), name='lemmatize'),
    path('lemma/', api_views.lemma, name='lemma'),
    path('synset/', api_views.synset, name='synset'),
    path('textparser-api/', api_views.textparser, name='textparser-api'),

]

infos/urls.py
from django.conf.urls import url
from . import views
from . import special_views

app_name = 'infos'
urlpatterns = [
    url(
        r'^project-team/$',
        special_views.TeamView.as_view(),
        name='project-team'
    ),
    url(
        r'^about-the-project/$',
        special_views.SpecialAboutView.as_view(),
        name='about-the-project'
    ),
    url(
        r'^about/$',
        views.AboutTheProjectListView.as_view(),
        name='about_browse'
    ),
    url(
        r'^about/detail/(?P<pk>[0-9]+)$',
        views.AboutTheProjectDetailView.as_view(),
        name='about_detail'
    ),
    url(
        r'^about/create/$',
        views.AboutTheProjectCreate.as_view(),
        name='about_create'
    ),
    url(
        r'^about/edit/(?P<pk>[0-9]+)$',
        views.AboutTheProjectUpdate.as_view(),
        name='about_edit'
    ),
    url(
        r'^about/delete/(?P<pk>[0-9]+)$',
        views.AboutTheProjectDelete.as_view(),
        name='about_delete'),
    url(
        r'^teammember/$',
        views.TeamMemberListView.as_view(),
        name='teammember_browse'
    ),
    url(
        r'^teammember/detail/(?P<pk>[0-9]+)$',
        views.TeamMemberDetailView.as_view(),
        name='teammember_detail'
    ),
    url(
        r'^teammember/create/$',
        views.TeamMemberCreate.as_view(),
        name='teammember_create'
    ),
    url(
        r'^teammember/edit/(?P<pk>[0-9]+)$',
        views.TeamMemberUpdate.as_view(),
        name='teammember_edit'
    ),
    url(
        r'^teammember/delete/(?P<pk>[0-9]+)$',
        views.TeamMemberDelete.as_view(),
        name='teammember_delete'),
    url(
        r'^projectinst/$',
        views.ProjectInstListView.as_view(),
        name='projectinst_browse'
    ),
    url(
        r'^projectinst/detail/(?P<pk>[0-9]+)$',
        views.ProjectInstDetailView.as_view(),
        name='projectinst_detail'
    ),
    url(
        r'^projectinst/create/$',
        views.ProjectInstCreate.as_view(),
        name='projectinst_create'
    ),
    url(
        r'^projectinst/edit/(?P<pk>[0-9]+)$',
        views.ProjectInstUpdate.as_view(),
        name='projectinst_edit'
    ),
    url(
        r'^projectinst/delete/(?P<pk>[0-9]+)$',
        views.ProjectInstDelete.as_view(),
        name='projectinst_delete'),
]

webpage/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

app_name = 'webpage'

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    url(r'^favicon\.ico$', favicon_view),
    url(r'^imprint', views.ImprintView.as_view(), name="imprint"),
    url(r'^$', views.GenericWebpageView.as_view(), name="start"),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^project-info/$', views.project_info, name='project_info'),
    url(r'^(?P<template>[\w-]+)/$', views.GenericWebpageView.as_view(), name='staticpage'),
]

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class form_user_login(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(form_user_login, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'login'))

webpage/views.py
from copy import deepcopy

import requests

from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import RequestContext, loader
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout

from . forms import form_user_login
from . metadata import PROJECT_METADATA as PM


def get_imprint_url():
    try:
        base_url = settings.ACDH_IMPRINT_URL
    except AttributeError:
        base_url = "https://provide-an-acdh-imprint-url/"
    try:
        redmine_id = settings.REDMINE_ID
    except AttributeError:
        redmine_id = "go-register-a-redmine-service-issue"
    return "{}{}".format(base_url, redmine_id)


class ImprintView(TemplateView):
    template_name = 'webpage/imprint.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        imprint_url = get_imprint_url()
        r = requests.get(get_imprint_url())

        if r.status_code == 200:
            context['imprint_body'] = "{}".format(r.text)
        else:
            context['imprint_body'] = """
            On of our services is currently not available. Please try it later or write an email to
            acdh@oeaw.ac.at; if you are service provide, make sure that you provided ACDH_IMPRINT_URL and REDMINE_ID
            """
        return context


class GenericWebpageView(TemplateView):
    template_name = 'webpage/index.html'

    def get_context_data(self, **kwargs):
        context = super(GenericWebpageView, self).get_context_data(**kwargs)
        context['apps'] = settings.INSTALLED_APPS
        return context

    def get_template_names(self):
        template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        try:
            loader.select_template([template_name])
            template_name = "webpage/{}.html".format(self.kwargs.get("template", 'index'))
        except:
            template_name = "webpage/index.html"
        return [template_name]


#################################################################
#               views for login/logout                          #
#################################################################

def user_login(request):
    if request.method == 'POST':
        form = form_user_login(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.GET.get('next', '/'))
            return HttpResponse('user does not exist')
    else:
        form = form_user_login()
        return render(request, 'webpage/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return render(request, "webpage/user_logout.html")


def handler404(request, exception):
    return render(request, 'webpage/404-error.html', locals())


def project_info(request):

    """
    returns a dict providing metadata about the current project
    """

    info_dict = deepcopy(PM)

    if request.user.is_authenticated:
        pass
    else:
        del info_dict['matomo_id']
        del info_dict['matomo_url']
    info_dict['base_tech'] = 'django'
    info_dict['framework'] = 'djangobaseproject'
    return JsonResponse(info_dict)

webpage/templates/webpage/404-error.html
{% extends "webpage/base.html" %}
{% load static %}

{% block content %}
<div class="container">
<div style="text-align: center;">
    
    <h2>We're sorry, the page you requested cannot be found.</h2>
    <p style="text-align: center">The page you're trying to access may not exist anymore or may have been moved. Try accessing it again from our site's homepage. Please also make sure that your spelling is correct.</p>
    <p style="text-align: center">If the problem persists, please report it as an issue <a href="https://github.com/acdh-oeaw/djangobaseproject/issues">here</a>. Thank you!</p>

</div>
</div>
{% endblock %}

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} About {% endblock %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title">{% projects_metadata 'title' %}</h1>
        </div>
        <div class="card-body">
            <div>
                <p>
                    {% projects_metadata 'description' %}
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

webpage/templates/webpage/base.html
<!DOCTYPE html>
{% load static %}
{% load webpage_extras %}
{% load browsing_extras %}
{% load infos_extras %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% projects_metadata 'title' %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block metaDescription %}
        <meta name="description" content="{{ metadata.description }}">
        <meta name="author" content="{{ metadata.author }}">
    {% endblock %}
    <!-- favicons -->
        <link rel="apple-touch-icon" sizes="180x180" href="{{ SHARED_URL }}favicon/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="{{ SHARED_URL }}favicon/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="{{ SHARED_URL }}favicon/favicon-16x16.png"/>
        <link rel="manifest" href="{{ SHARED_URL }}favicon/manifest.json"/>
        <link rel="mask-icon" href="{{ SHARED_URL }}favicon/safari-pinned-tab.svg" color="#00aba9"/>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css" />
	<meta name="theme-color" content="#ffffff"/>
    <!--favicons end -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin:400,500" rel="stylesheet" />
    <link rel="stylesheet" id="fundament-styles"  href="{{ SHARED_URL }}fundament/dist/fundament/css/fundament.min.css" type="text/css"/>
    <link rel="stylesheet" href="{% static 'webpage/css/style.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{{ SHARED_URL }}apis/libraries/scroll-to-top/css/ap-scroll-top.min.css" />
    <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
    <script type="text/javascript">
        window.cookieconsent_options = {
            "message":"This website uses cookies to ensure you get the best experience on our website",
            "dismiss":"Got it!",
            "learnMore":"More info",
            "link":"{% projects_metadata 'imprint' %}",
            "theme":"dark-bottom"};
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
    <!-- End Cookie Consent plugin -->
    <!-- Matomo -->
      <script type="text/javascript">
        var _paq = _paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
          var u="{% projects_metadata 'matomo_url' %}";
          _paq.push(['setTrackerUrl', u+'piwik.php']);
          _paq.push(['setSiteId', '{% projects_metadata "matomo_id" %}']);
          var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
          g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
        })();
      </script>
    <!-- End Matomo Code -->
    {% block scriptHeader %}
    {% endblock %}
</head>
<body role="document" class="home contained fixed-nav" id="body">
    <div class="hfeed site" id="page">
        <div class="wrapper-fluid wrapper-navbar sticky-navbar" id="wrapper-navbar" itemscope="" itemtype="http://schema.org/WebSite">
            <a class="skip-link screen-reader-text sr-only" href="#content">Skip to content</a>
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">
                    <!-- Your site title as branding in the menu -->
                    <a href="/" class="navbar-brand custom-logo-link" rel="home" itemprop="url">
                        <img src="{{ PROJECT_LOGO }}" class="img-fluid" alt="{% projects_metadata 'title' %}" itemprop="{% projects_metadata 'title' %}"/>
                    </a><!-- end custom logo -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"/>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                        <!-- Your menu goes here -->
                        <ul id="main-menu" class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About
                                    <span class="caret"/>
                                </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{% url 'infos:about-the-project' %}">About the project</a>
                                        <a class="dropdown-item" href="{% url 'infos:project-team' %}">Team</a>
                                        <a class="dropdown-item" href="{% url 'webpage:staticpage' template='imprint' %}">Imprint | Impressum</a>
                                    </div>
                                </li>
                                {% if 'vocabs' in APPS %}
                                    {% if user.is_authenticated %}
                                        <li class="nav-item dropdown">
                                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vocabs Curation
                                        <span class="caret"/>
                                        </a>
                                            <div class="dropdown-menu">
                                                {% nav_menu app='vocabs' as links %}
                                                {% for x in links %}
                                                    <a class="dropdown-item" href="{{ x.link }}">{{ x.name }}</a>
                                                {% endfor %}
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="{% url 'api-root' %}">Export SKOS (API)</a>
                                            </div>
                                        </li>
                                    {% endif %}
                                {% endif %}
                            </ul>
                            <ul class="navbar-nav justify-content-end">
                                {% if user.is_authenticated %}
                                <li class="nav-item dropdown ml-auto">
                                    <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        {{ user.get_username }}
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="nav-link" href="{% url 'webpage:user_logout' %}">log out <i class="feather-32" data-feather="log-out"></i></a>
                                    </div>
                                </li>
                                {% else %}
                                <li class="nav-item dropdown my-2 my-lg-0">
                                    <a class="nav-link" href="{% url 'webpage:user_login' %}">
                                    <i class="feather-32" data-feather="log-in"></i>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                        <!-- .collapse navbar-collapse -->
                    </div>
                    <!-- .container -->
                </nav>
                <!-- .site-navigation -->
            </div>
            <div id="content">
                {% if DEV_VERSION %}
                <div class="alert alert-danger" role="alert">
                    This is a DEVELOPMENT instance. Click <a href="https://{{ PROJECT_NAME }}.acdh.oeaw.ac.at">here</a> for the Production version
                </div>
                {% endif %}
                {% block content %}{% endblock %}
            </div>
            <div class="wrapper fundament-default-footer" id="wrapper-footer-full">
                <div class="container-fluid" id="footer-full-content" tabindex="-1">
                    <div class="footer-separator">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-message-circle">
                            <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/>
                        </svg> KONTAKT
                    </div>
                    <div class="row justify-content-md-center" style="text-align:center">
                        <div class="col">
                            <a href="https://www.oeaw.ac.at/acdh/" target="_blank" rel="noopener" aria-label="ACDH">
                                <img src="https://fundament.acdh.oeaw.ac.at/common-assets/images/acdh_logo.svg" alt="ACDH" title="Austrian Centre for Digital Humanities (ACDH) of the Austrian Academy of Sciences"/>
                            </a>
                            <br />
                            Austrian Centre for Digital Humanities (ACDH) of the Austrian Academy of Sciences
                        </div>
                        {% project_insts as insts %}
                        {% for x in insts %}
                            <div class="col">
                                <a href="{{ x.website }}" target="_blank" rel="noopener" aria-label="{{ x.abbr }}">
                                    <img src="{{ x.logo_url}}" alt="{{ x.abbr }}" title="{{ x.name }}">
                                </a>
                                <br />
                                {{ x.name }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="footer-imprint-bar" id="wrapper-footer-secondary" style="text-align:center; padding:0.4rem 0; font-size: 0.9rem;">
                <a href="imprint.html">Impressum/Imprint</a>
                {% if user.is_authenticated %}
                    {% if DB_NAME %}
                        <div class="footer-imprint-bar">
                            <small>{{ DB_NAME }}</small>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
            {% block scripts %}
                <script src="{{ SHARED_URL }}fundament/dist/fundament/js/fundament.min.js"></script>
        	    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
                <script src="{{ SHARED_URL }}apis/libraries/scroll-to-top/js/ap-scroll-top.min.js"></script>
            {% endblock %}
            {% block scripts2 %}
            {% endblock scripts2 %}
    </body>
</html>

webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong>{{ object }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn" type="submit" value="No, bring me back" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

webpage/templates/webpage/generic_create.html
{% extends "webpage/create_base_template.html" %}
{% block title %}
    Create/Edit {{ class_name }}
{% endblock %}

{% block objectType %}
    <h1>Create/Edit
        {% if docstring %}
            <abbr title="{{ docstring}}">{{ class_name }}</abbr>
        {% else %}
            {{ class_name }}
        {% endif %}
    </h1>
{% endblock %}

webpage/templates/webpage/generic_list.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% load django_tables2 %}
{% load browsing_extras %}
{% load i18n %}
{% load crispy_forms_field %}
{% load crispy_forms_tags %}
{% block Titel %} Browse {{ class_name }} {% endblock %}
{% block scriptHeader %}
{% endblock %}
{% block content %}

<script type="text/javascript">
$(document).ready(function() {
var fetchedParameter = "{{ table.page.number }}";
$("#goto option").each(function() {
    if($(this).text() == fetchedParameter) {
        $(this).attr('selected', 'selected');
    }
});
});
</script>
<style>

</style>
<div class="container-fluid">

        <h1 style="margin-bottom:15px; margin-top:15px;"><i class="fas fa-search" style="padding-left:10px; padding-right: 10px;"></i>Browse {% class_definition %} {% block list_title %}{% endblock %}</h1>
        {% if get_arche_dump %}
            <a class ="btn btn-outline-secondary"  href="{{ get_arche_dump}}{% querystring %}">Dump as RDF</a>
        {% endif %}
        {% if dl_csv_link %}
            <a class ="btn btn-outline-secondary"  href="{{ dl_csv_link}}{% querystring %}">Dump as CSV</a>
        {% endif %}
        {% if user.is_authenticated %}
            {% if create_view_link  %}
                <a class ="btn btn-outline-secondary"  href="{{ create_view_link }}">Create new {{class_name}}</a>
            {% endif %}
        {% endif %}
    {% block customView %}{% endblock %}
    {% block create_button %}{% endblock %}

        <div class="row">
            <div class="col-md-4">
            <div class="card">
            <div class="card-body">
                {% load django_tables2 crispy_forms_tags %}
            <form action="." class="uniForm" method="get">
                {% if togglable_colums %}
                    <legend>Select additional columns</legend>
                    {% column_selector  %}
                    {% endif %}
                <br/>
                {% crispy filter.form filter.form.helper %}
            </form>
          {% block reset_button %}
          <a class ="btn btn-outline-secondary"  href=".">Reset search</a>
          {% endblock %}
            </div>
            </div>
            </div>
            <div class="col-md-8" id="results">
            <div class="card">
            <div class="card-body">
    {% with table.paginator.count as total %}
    <legend>Total results: {{ total }}</legend>
    {% endwith %}


      {% block table %}
      <table class="table" {% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
          {% block table.thead %}
          {% if table.show_header %}
          <thead>
              <tr>
              {% for column in table.columns %}
                  {% if column.orderable %}
                  <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a></th>
                  {% else %}
                  <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
                  {% endif %}
              {% endfor %}
              </tr>
          </thead>
          {% endif %}
          {% endblock table.thead %}
          {% block table.tbody %}
          <tbody>
              {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
              {% block table.tbody.row %}
              <tr {{ row.attrs.as_html }}>
                  {% for column, cell in row.items %}
                  <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>

                  {% endfor %}
              </tr>
              {% endblock table.tbody.row %}
              {% empty %}
              {% if table.empty_text %}
              {% block table.tbody.empty_text %}
              <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
              {% endblock table.tbody.empty_text %}
              {% endif %}
              {% endfor %}
          </tbody>
          {% endblock table.tbody %}
          {% block table.tfoot %}
          {% if table.has_footer %}
          <tfoot>
              <tr>
              {% for column in table.columns %}
                  <td>{{ column.footer }}</td>
              {% endfor %}
              </tr>
          </tfoot>
          {% endif %}
          {% endblock table.tfoot %}
      </table>
      {% endblock table %}

      {% block pagination.allpages %}

      <div>
      {% with table.page.object_list|length as count %}
      <p>Page total: {{ count }}</p>
      {% endwith %}
      </div>

      <ul class="pagination">


<!--if more than 15 pages switches to select page form -->

        {% if table.paginator.page_range|length > 10 %}

<!--if has previous page - previous button -->

        {% if table.page.has_previous %}
        {% block pagination.previous.goto %}
        <li class="previous">
          <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}">{% trans "Previous" %}</a>
        </li>
        {% endblock pagination.previous.goto %}
        {% endif %}


<!--select form if more than 15 pages -->

<div class="form-group">
  <label for="goto">Go to page</label>
    <select class="form-control" id="goto" onchange="javascript:location.href = this.value;">
        {% for p in table.paginator.page_range %}
            <option value="{% querystring table.prefixed_page_field=p %}">{{ p }}</option>
        {% endfor %}
    </select>



</div>


<!--Page # of total -->
{% if table.page.has_previous or table.page.has_next %}
{% block pagination.cardinality %}
{% blocktrans with table.page.number as current and table.paginator.num_pages as total %}
<p>Page {{ current }} of {{ total }}</p>
{% endblocktrans %}
{% endblock pagination.cardinality %}
{% endif %}

<!--if has next page - next button -->

{% if table.page.has_next %}
{% block pagination.next.goto %}
  <li class="next">
  <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" style="border-radius: 0px;">{% trans "Next" %}</a>
  </li>
{% endblock pagination.next.goto %}
{% endif %}


<!--else condition  - if less than 15 pages  - shows page number buttons-->

        {% else %}


        {% if table.page.has_previous %}
        {% block pagination.previous %}
        <li class="previous">
          <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}">{% trans "Previous" %}</a>
        </li>
        {% endblock pagination.previous %}
        {% endif %}

        {% for p in table.paginator.page_range %}
        {% if p == table.page.number %}
        <li><a href="{% querystring table.prefixed_page_field=p %}" style="background-color:#007bff; border-color: #2e6da4; color: #ffffff; padding: 5px 10px 5px 10px;">{{ p }}</a>
        </li>
         {% else %}
        <li>
          <a href="{% querystring table.prefixed_page_field=p %}"> {{ p }}</a>
        </li>
        {% endif %}
        {% endfor %}


        {% if table.page.has_next %}
        {% block pagination.next %}
          <li class="next">
          <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}">{% trans "Next" %}</a>
          </li>
        {% endblock pagination.next %}
        {% endif %}


        {% endif %}


      </ul>
      {% endblock pagination.allpages %}

  </div>
        </div>
        </div>
        </div>
</div>

{% endblock %}

webpage/templates/webpage/imprint.html
{% extends "webpage/base.html" %}
{% load static %}
{% load webpage_extras %}
{% block title %} Imprint {% endblock %}
{% block content %}
<div class="container">
<div class="card imprint">
<div class="card-body">
    {{ imprint_body|safe }}
</div>
</div>
</div>
{% endblock %}

webpage/templates/webpage/index.html
{% extends "webpage/base.html" %}
{% load static %}
{% load stats_extras %}
{% load webpage_extras %}
{% block content %}

        <div class="jumbotron" style="background-image: url({% static 'webpage/img/project_background.jpg' %}) ">
            <div class="container">
                <h1 style="text-align:center; color: #111;">{% projects_metadata 'title' %}</h1>
                <h3 style="text-align:center; color: #111;">{% projects_metadata 'subtitle' %}</h3>
                <h5 style="text-align:center; color: #111;">{% projects_metadata 'description' %}</h5>
            </div>
        </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12" style="text-align:center">
                <h4>Data-Count</h4>
            </div>
            {% create_object_count app='vocabs' as models %}
            {% for x in models %}
                <div class="col-md-4  text-center">
                    <div class="card flex-md-row mb-4 box-shadow">
                        <div class="card-body">
                            <h4 class="mb-0">{{x.name}}</h4>
                            <h4 class="count">{{ x.count }}</h4>
                            {% if x.link %}
                                <a class="btn btn-main btn-outline-primary btn-sm" href="{{ x.link }}" role="button">View Details</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

webpage/templates/webpage/user_login.html
{% extends "webpage/base.html" %}
{% block content %}
<div class="container">
    <br />
    {% if form.errors %}
        <p style="color:red;">Please correct the error{{ form.errors|pluralize }} below.</p>
    {% endif %}
    {% load crispy_forms_tags %}
    {% crispy form form.helper %}
</div>
{% endblock %}